# Generated by Django 3.2.25 on 2024-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20240514_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
