# Generated by Django 3.2.25 on 2024-05-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial_number', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serialnumber',
            old_name='partnering_end',
            new_name='link_partnering_end',
        ),
        migrations.RenameField(
            model_name='serialnumber',
            old_name='product',
            new_name='link_product_name',
        ),
    ]
