# Generated by Django 3.2.25 on 2024-05-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotpost',
            name='image',
            field=models.ImageField(default='../default_post_y8afhe', upload_to='images/'),
        ),
    ]
